# Generated by Django 5.1.6 on 2025-02-15 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kenya_counties',
            options={'verbose_name_plural': 'Kenya Counties'},
        ),
        migrations.AlterModelOptions(
            name='kenya_coutry',
            options={'verbose_name_plural': 'Kenya Countries'},
        ),
        migrations.AlterModelOptions(
            name='kenya_subcounty',
            options={'verbose_name_plural': 'Kenya Subcounties'},
        ),
    ]
