# Generated by Django 5.1.6 on 2025-02-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_kenya_counties_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kenya_counties',
            new_name='KenyaCountry',
        ),
        migrations.RenameModel(
            old_name='Kenya_coutry',
            new_name='KenyaCounty',
        ),
        migrations.RenameModel(
            old_name='Kenya_subcounty',
            new_name='KenyaSubcounty',
        ),
        migrations.AlterModelOptions(
            name='kenyacountry',
            options={'verbose_name_plural': 'Kenya Country'},
        ),
        migrations.AlterModelOptions(
            name='kenyacounty',
            options={'verbose_name_plural': 'Kenya Counties'},
        ),
        migrations.RenameField(
            model_name='kenyacountry',
            old_name='adm1_en',
            new_name='adm0_en',
        ),
        migrations.RenameField(
            model_name='kenyacounty',
            old_name='adm0_en',
            new_name='adm1_en',
        ),
    ]
