# Generated by Django 5.1.6 on 2025-02-17 07:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_kenya_counties_kenyacountry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('kmfl_new', models.CharField(max_length=254)),
                ('kmfl', models.CharField(max_length=254)),
                ('nn_field', models.BigIntegerField()),
                ('county', models.CharField(max_length=254)),
                ('constituen', models.CharField(max_length=254)),
                ('sub_county', models.CharField(max_length=254)),
                ('ward', models.CharField(max_length=254)),
                ('keph_level', models.CharField(max_length=254)),
                ('ownership', models.CharField(max_length=254)),
                ('qq2', models.CharField(max_length=254)),
                ('q2', models.CharField(max_length=254)),
                ('qq3', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Hospitals',
            },
        ),
    ]
