# Generated by Django 5.1.6 on 2025-02-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_hospitals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='constituen',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='sub_county',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='ward',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
