# Generated by Django 5.1.6 on 2025-02-18 08:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_level4_buffer_level5_buffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level4_buffer',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='level5_buffer',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
